---
- name: Install K3s worker and join cluster
  shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['master'][0]]['inventory_hostname'] }}:6443 K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_token'] }} sh -"
  args:
    creates: /var/lib/rancher/k3s/agent/kubelet.kubeconfig